---
  - name: upload laravel app on debian 11
    hosts: all
    tasks:
      - name: install curl
        apt:
          name: curl
          state: present
      - name: copy files
        ansible.builtin.copy:
          src: /root/bash.sh
          dest: /root
          mode: 777
      - name: execute script
        command: /root/bash.sh

      - name: move composer
        command: mv /root/composer.phar /usr/local/bin/composer
      
      - name: change permission
        command: chmod +x /usr/local/bin/composer

      - name: install git
        apt:
          name: git
          state: present
      - name: deploy app from master
        ansible.builtin.copy:
          src: /root/demo.conf
          dest: /etc/apache2/sites-availabe
      - name: clone 
        ansible.builtin.git:
          repo: https://github.com/f1amy/laravel-realworld-example-app.git
          dest: /var/www/laravel

      - name: connet to mysql
        ansible.builtin.copy:
          src: /root/mysql.sh
          dest: /root
      - name: enable site
        command: a2ensite demo.conf

      - name: restart apache2
        command: systemctl reload apache2


      - name: set storage permision
        command: "{{ item }}"
        with_items:
          - chown -R :www-data /var/www/laravel
          - chmod -R 775 /var/www/laravel
          - chmod -R 775 /var/www/laravel/storage

      - name: run composer
        composer:
          command: install
          working_dir: /var/www/laravel
        environment:
          COMPOSER_ALLOW_SUPERUSER: "1"
          COMPOSER_NO_INTERACTION: "1"

      - name: generate app keys
        composer:
          command: create-project
          working_dir: /var/www/laravel
        environment:
          COMPOSER_ALLOW_SUPERUSER: "1"
          COMPOSER_NO_INTERACTION: "1"
        


